# Header Menu
menu:
  Home: /
  Case Studies: /tags/Case-Studies/
  Blog: /blog/ # can set archive-dir in root config to custom value
  Team: /team/
  Services: /services/
  Contact: /contact/
  
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/lingqingmeng
  twitter: https://twitter.com/lingqingmeng
  facebook: https://www.facebook.com/lingqingmeng
  rss: atom.xml
  linkedin: https://www.linkedin.com/in/ling-qing-meng-90a35552/
  stackoverflow: https://stackoverflow.com/users/2163873/ling-qing-meng

# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "947183761371807744" # as a string, from https://twitter.com/settings/widgets
twitter_username: lingqingmeng # twitter username without the @
default_author: Anonymous

about: Decentral Solutions © offers security services to companies using blockchain technologies. We help teams launch and manage ICOs, deploy secure dApps, and integrate private networks into business practices.<br><br> Our team has roots in traditional cybersecurity, originally consulting to large international institutes, ranging from the financial to healthcare sector. In addition each partner brings domain expertise in the fields of distributed systems, network architecture, scalability, and latest methodologies in frontend development. <br><br> We understand the emerging threats that companies face in the unregulated and high value space of cryptocurrencies. Our solutions are crafted to address these issues in the most effective ways possible. <br><br>
phone: (650)383-0295
email: hello@decentral.solutions
address_1: 1489 Webster St
address_2: 6th Floor
address_3: San Francisco, CA 94115
skype: video@decentral.solutions
lat: 37.783953
long: -122.431967
